<?php

namespace ContainerNq4Kv7i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U623HZOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u623HZO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u623HZO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'transaction' => ['privates', '.errored..service_locator.u623HZO.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.u623HZO": it references class "App\\Entity\\Transaction" but no such service exists.'],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
        ], [
            'transaction' => 'App\\Entity\\Transaction',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
        ]);
    }
}
