<?php

namespace ContainerNq4Kv7i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AuFZtvMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AuFZtvM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AuFZtvM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'moyenDePaiement' => ['privates', '.errored..service_locator.AuFZtvM.App\\Entity\\MoyenDePaiement', NULL, 'Cannot autowire service ".service_locator.AuFZtvM": it references class "App\\Entity\\MoyenDePaiement" but no such service exists.'],
            'moyenDePaiementRepository' => ['privates', 'App\\Repository\\MoyenDePaiementRepository', 'getMoyenDePaiementRepositoryService', true],
        ], [
            'moyenDePaiement' => 'App\\Entity\\MoyenDePaiement',
            'moyenDePaiementRepository' => 'App\\Repository\\MoyenDePaiementRepository',
        ]);
    }
}
