<?php

namespace ContainerNq4Kv7i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Am9I1DnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Am9I1Dn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Am9I1Dn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'moyenDePaiementRepository' => ['privates', 'App\\Repository\\MoyenDePaiementRepository', 'getMoyenDePaiementRepositoryService', true],
        ], [
            'moyenDePaiementRepository' => 'App\\Repository\\MoyenDePaiementRepository',
        ]);
    }
}
