<?php

namespace ContainerNq4Kv7i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoyenDePaiementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AuFZtvM.App\Entity\MoyenDePaiement' shared service.
     *
     * @return \App\Entity\MoyenDePaiement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AuFZtvM": it references class "App\\Entity\\MoyenDePaiement" but no such service exists.');
    }
}
