<?php

namespace ContainerLv3uG1E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y28UDvdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y28UDvd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y28UDvd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'transaction' => ['privates', '.errored..service_locator.Y28UDvd.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.Y28UDvd": it references class "App\\Entity\\Transaction" but no such service exists.'],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'typeRepository' => ['privates', 'App\\Repository\\TypeRepository', 'getTypeRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'em' => '?',
            'transaction' => 'App\\Entity\\Transaction',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'typeRepository' => 'App\\Repository\\TypeRepository',
        ]);
    }
}
