<?php

namespace ContainerLv3uG1E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransaction2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y28UDvd.App\Entity\Transaction' shared service.
     *
     * @return \App\Entity\Transaction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Y28UDvd": it references class "App\\Entity\\Transaction" but no such service exists.');
    }
}
